
server:
  port: 9090

  spring:
    h2:
      console:
        enabled: true
        path: /h2
    datasource:
      url: jdbc:h2:~/test
      username: sa
      password:
      driverClassName: org.h2.Driver

  jpa:
    hibernate:
       ddl-auto: update
    properties:
       hibernate:
         format_sql: true
    show-sql: true
